# Introducción a los tensores con Tensorflow y Numpy

In [1]:
import tensorflow as tf
import numpy as np

Esenciales

In [2]:
t0 = tf.constant(7)
print(t0)

tf.Tensor(7, shape=(), dtype=int32)


In [4]:
t1 = tf.constant([1,5,9])
print(t1)

tf.Tensor([1 5 9], shape=(3,), dtype=int32)


In [9]:
t2 = tf.constant([[1,2,2],[3,4,5]])
print(t2)

tf.Tensor(
[[1 2 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [12]:
t3 = tf.constant([[[1,1]],[[2,2]],[[3,3]]])
print(t3)

tf.Tensor(
[[[1 1]]

 [[2 2]]

 [[3 3]]], shape=(3, 1, 2), dtype=int32)


In [14]:
t3.numpy()

array([[[1, 1]],

       [[2, 2]],

       [[3, 3]]])

In [16]:
t3.numpy().shape

(3, 1, 2)

In [17]:
t3.shape

TensorShape([3, 1, 2])

Algebra de tensores

In [18]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
print(a)
print(b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [20]:
print(tf.add(a,b))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [21]:
print(tf.multiply(a,b))

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [22]:
print(tf.matmul(a,b))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [23]:
print(tf.matmul(b,a))

tf.Tensor(
[[23 34]
 [31 46]], shape=(2, 2), dtype=int32)


In [24]:
print(a+b)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [25]:
print(a*b)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [26]:
print(a@b)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


Funciones de reduccion

In [27]:
c = tf.constant([[4,5],[10,1]])
print(c)

tf.Tensor(
[[ 4  5]
 [10  1]], shape=(2, 2), dtype=int32)


In [28]:
print(tf.reduce_max(c))

tf.Tensor(10, shape=(), dtype=int32)


In [29]:
print(tf.reduce_min(c))

tf.Tensor(1, shape=(), dtype=int32)


In [31]:
print(tf.reduce_mean(c))

tf.Tensor(5, shape=(), dtype=int32)


In [32]:
print(tf.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [37]:
print(tf.nn.softmax(tf.dtypes.cast(c, tf.float16)))

tf.Tensor(
[[2.690e-01 7.310e-01]
 [1.000e+00 1.234e-04]], shape=(2, 2), dtype=float16)


In [38]:
print(tf.reduce_sum(tf.nn.softmax(tf.dtypes.cast(c, tf.float16))))

tf.Tensor(2.0, shape=(), dtype=float16)


In [39]:
print(tf.reduce_sum(tf.nn.softmax(tf.dtypes.cast(c, tf.float16)),axis=0))

tf.Tensor([1.27  0.731], shape=(2,), dtype=float16)


In [40]:
print(tf.reduce_sum(tf.nn.softmax(tf.dtypes.cast(c, tf.float16)),axis=1))

tf.Tensor([1. 1.], shape=(2,), dtype=float16)


Tipo, forma y dimension

In [41]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print(t)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [43]:
print(t.dtype)

<dtype: 'int32'>


In [45]:
print(t.shape)

(3, 2, 5)


In [46]:
print(t.ndim)

3


In [47]:
print(t.shape[2])

5


In [48]:
print(tf.size(t.numpy()))

tf.Tensor(30, shape=(), dtype=int32)


Indexacion

En un solo eje

In [49]:
t1 =  tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print("Primero: ", t1[0])
print("Segundo: ", t1[1])
print("Ultimo: ", t1[-1].numpy())

Primero:  tf.Tensor(0, shape=(), dtype=int32)
Segundo:  tf.Tensor(1, shape=(), dtype=int32)
Ultimo:  34


Extraccion de parte de un tensro: slides

In [50]:
print(t1[:])

tf.Tensor([ 0  1  1  2  3  5  8 13 21 34], shape=(10,), dtype=int32)


In [56]:
print(t1[:4])

tf.Tensor([0 1 1 2], shape=(4,), dtype=int32)


In [57]:
print(t1[4:])

tf.Tensor([ 3  5  8 13 21 34], shape=(6,), dtype=int32)


In [58]:
print(t1[4:7])

tf.Tensor([3 5 8], shape=(3,), dtype=int32)


In [60]:
print(t1[::2])

tf.Tensor([ 0  1  3  8 21], shape=(5,), dtype=int32)


In [61]:
print(t1[::-1])

tf.Tensor([34 21 13  8  5  3  2  1  1  0], shape=(10,), dtype=int32)


Indexacion multieje

In [62]:

t23 = tf.constant([[1, 2, 3],[4, 5, 6]])
print(t23.numpy())

[[1 2 3]
 [4 5 6]]


In [63]:
print(t23[1,1].numpy())

5


In [73]:
print(t23[1,:].numpy())

[4 5 6]


In [77]:
print(t23[:,2].numpy())

[3 6]


In [85]:
print(t23[:,0:2].numpy())

[[1 2]
 [4 5]]


In [93]:
print(t23[:,:2].numpy())

[[1 2]
 [4 5]]


In [94]:
t = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],]) 
print(t.numpy())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [96]:
print(t[1,:,:].numpy())

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [97]:
print(t[1].numpy())

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [102]:
print(t[2,:,1:3].numpy())

[[21 22]
 [26 27]]


Manipular formas

In [103]:
x = tf.constant([[1],[2],[3]])
print(x)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [104]:
print(x.shape.as_list())

[3, 1]


In [105]:
reshaped = tf.reshape(x, [1,3])
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


Aplanar un tensor

In [106]:
print(t)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [107]:
flat = tf.reshape(t,[-1])
print(flat)

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [108]:
print(tf.reshape(t,[2,3*5]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]], shape=(2, 15), dtype=int32)


In [113]:
print(tf.reshape(t, [-1,5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


Cast. Conversion de tipos

In [114]:
f64_tensor = tf.constant([2.0, 4.0, 6.0], dtype = tf.float64)
print(f64_tensor)

f16_tensor = tf.cast(f64_tensor,dtype= tf.float16)
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype = tf.uint8)
print(u8_tensor)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float64)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float16)
tf.Tensor([2 4 6], shape=(3,), dtype=uint8)


Radiodifusión. Broadcasting

In [115]:
x = tf.constant([1, 2 ,3])
y = tf.constant(2)
z = tf.constant([2, 2 ,2])

# el mismo resultado
print(tf.multiply(x,2))
print(x*y)
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Tensores irregulares

In [116]:

ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [117]:
try:
    tensor = tf.constant(ragged_list)
except Exception as e:
     print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [119]:
ragged_t = tf.ragged.constant(ragged_list)

print(ragged_t)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


Tensores de strings

In [120]:

st = tf.constant(["Este tensor string",
                 "Cadena 2",
                 "Cadena 3",
                 "🥳"])
print(st)

tf.Tensor([b'Este tensor string' b'Cadena 2' b'Cadena 3' b'\xf0\x9f\xa5\xb3'], shape=(4,), dtype=string)


In [121]:

st_split = tf.strings.split(st)
for i in st_split:
    print(i)

tf.Tensor([b'Este' b'tensor' b'string'], shape=(3,), dtype=string)
tf.Tensor([b'Cadena' b'2'], shape=(2,), dtype=string)
tf.Tensor([b'Cadena' b'3'], shape=(2,), dtype=string)
tf.Tensor([b'\xf0\x9f\xa5\xb3'], shape=(1,), dtype=string)


Tensor disperso

In [122]:
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                                       values = [1,2],
                                       dense_shape
                                        =[3,4])
print(sparse_tensor, "\n")

# convierte a tensor denso
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
